apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-api
  namespace: python-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - python-api.167.179.41.65.sslip.io
      secretName: python-api-tls-cert
  rules:
    - host: python-api.167.179.41.65.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-api
                port:
                  number: 80